apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    supplementalGroups: [1000]
  containers:
  - name: spark-kubernetes-executor
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
    volumeMounts:
    - name: data-nfs
      mountPath: /data
    env:
    - name: SPARK_USER
      value: "spark"
  volumes:
  - name: data-nfs
    persistentVolumeClaim:
      claimName: data-nfs
  tolerations:
  - effect: "NoSchedule"
    key: "k8s.dask.org/dedicated"
    operator: "Equal"
    value: "worker"
  - effect: "NoSchedule"
    key: "k8s.dask.org_dedicated"
    operator: "Equal"
    value: "worker"
  nodeSelector:
    k8s.dask.org/node-purpose: "worker"