apiVersion: garden.io/v1
kind: Project
name: teehr-hub
defaultEnvironment: local

variables:

environments:
  - name: local
    defaultNamespace: ${project.name}
    variables:
      hostname: teehr.local.app.garden
      devTeehrVersion: e4fdea806f4c8e7afd30ff87bf53d71889321be8
      iceberg:
        inCluster: "true"
        catalogS3PathStyleAccess: "true"
        catalogS3Endpoint: "http://minio:9000"
        catalogType: rest
        catalogUri: http://iceberg-rest:8181
        catalogWarehouse: s3://warehouse/
      trino:
        host: trino
        port: 8080
        user: teehr
        catalog: iceberg
        schema: teehr
  - name: remote
    defaultNamespace: ${project.name}
    variables:
      hostname: teehr.rtiamanzi.org
      devTeehrVersion: e4fdea806f4c8e7afd30ff87bf53d71889321be8
      stableTeehrVersion: v0.6-dev
      previousTeehrVersion: v0.5.0
      iceberg:
        inCluster: "false"
        catalogS3PathStyleAccess: "false"
        catalogS3Endpoint: ""
        catalogUri: http://iceberg-rest:8181
        catalogType: rest
        catalogWarehouse: s3://dev-teehr-iceberg-warehouse/
      nfsServerDns: "fs-0cb715f5b7a76e862.efs.us-east-2.amazonaws.com"
      trino:
        host: trino
        port: 8080
        user: teehr
        catalog: iceberg
        schema: teehr
providers:
  # The name of the provider plugin to use.
  - name: local-kubernetes
    namespace: ${environment.namespace}
    environments: ["local"]
    setupIngressController: false
    deploymentRegistry:
      hostname: localhost:5001
      namespace: ${project.name}
    context: kind-kind
  - name: kubernetes
    namespace: ${environment.namespace}
    environments: ["remote"]
    imagePullSecrets:
      - name: ecr-config
        namespace: default
    deploymentRegistry:
      hostname: 935462133478.dkr.ecr.us-east-2.amazonaws.com
      namespace: ${project.name}
    context: arn:aws:eks:us-east-2:935462133478:cluster/teehr-hub
    buildMode: cluster-buildkit
    defaultHostname: teehr.rtiamanzi.org