apiVersion: garden.io/v1
kind: Project
name: teehr-hub
defaultEnvironment: local

variables:

environments:
  - name: local
    defaultNamespace: ${project.name}
    variables:
      hostname: teehr.local.app.garden
      devTeehrVersion: b437b5f99deba6c5d1775bfac6ea4fe0985338e7
      iceberg:
        inCluster: "true"
        catalogType: rest
        catalogUri: http://iceberg-rest:8181
        catalogWarehouse: s3://warehouse/
  - name: remote
    defaultNamespace: ${project.name}
    variables:
      hostname: teehr.rtiamanzi.org
      devTeehrVersion: b437b5f99deba6c5d1775bfac6ea4fe0985338e7
      stableTeehrVersion: v0.6-dev
      previousTeehrVersion: v0.5.0
      iceberg:
        inCluster: "false"
        catalogUri: "http://dev-teehr-sys-iceberg-alb-2105268770.us-east-2.elb.amazonaws.com"
        catalogType: rest
        catalogWarehouse: "s3://dev-teehr-sys-iceberg-warehouse/warehouse/"
      nfsServerDns: "fs-0cb715f5b7a76e862.efs.us-east-2.amazonaws.com"
providers:
  # The name of the provider plugin to use.
  - name: local-kubernetes
    namespace: ${environment.namespace}
    environments: ["local"]
    setupIngressController: false
    deploymentRegistry:
      hostname: localhost:5001
      namespace: ${project.name}
    context: kind-kind
  - name: kubernetes
    namespace: ${environment.namespace}
    environments: ["remote"]
    imagePullSecrets:
      - name: ecr-config
        namespace: default
    deploymentRegistry:
      hostname: 935462133478.dkr.ecr.us-east-2.amazonaws.com
      namespace: ${project.name}
    context: arn:aws:eks:us-east-2:935462133478:cluster/teehr-hub
    buildMode: cluster-buildkit
    defaultHostname: teehr.rtiamanzi.org