// Helper function to get metric label display name
export const getMetricLabel = (metric) => {
  const labels = {
    count: "Count",
    average: "Average",
    relative_bias: "Relative Bias",
    relative_mean: "Relative Mean",
    relative_median: "Relative Median",
    relative_minimum: "Relative Minimum",
    relative_maximum: "Relative Maximum",
    relative_standard_deviation: "Relative Standard Deviation",
    pearson_correlation: "Pearson Correlation",
    nash_sutcliffe_efficiency: "Nash-Sutcliffe Efficiency",
    kling_gupta_efficiency: "Kling-Gupta Efficiency",
  };
  return labels[metric] || metric;
};

export const metricScales = {
  relative_bias: {
    colors: [
      "#4575b4",
      "#91bfdb",
      "#e0f3f8",
      "#f7f7f7",
      "#fee090",
      "#fc8d59",
      "#d73027",
    ],
    stops: [-1, -0.5, -0.1, 0, 0.1, 0.5, 1],
    labels: [
      "Very Underpredicted",
      "Underpredicted",
      "Slightly Under",
      "No Bias",
      "Slightly Over",
      "Overpredicted",
      "Very Overpredicted",
    ],
  },
  relative_mean: {
    colors: [
      "#4575b4",
      "#91bfdb",
      "#e0f3f8",
      "#f7f7f7",
      "#fee090",
      "#fc8d59",
      "#d73027",
    ],
    stops: [0, 0.5, 0.9, 1, 1.1, 1.5, 2],
    labels: [
      "Much Lower",
      "Lower",
      "Slightly Lower",
      "Near Match",
      "Slightly Higher",
      "Higher",
      "Much Higher",
    ],
  },
  relative_median: {
    colors: [
      "#4575b4",
      "#91bfdb",
      "#e0f3f8",
      "#f7f7f7",
      "#fee090",
      "#fc8d59",
      "#d73027",
    ],
    stops: [0, 0.5, 0.9, 1, 1.1, 1.5, 2],
    labels: [
      "Much Lower",
      "Lower",
      "Slightly Lower",
      "Near Match",
      "Slightly Higher",
      "Higher",
      "Much Higher",
    ],
  },
  relative_minimum: {
    colors: [
      "#4575b4",
      "#91bfdb",
      "#e0f3f8",
      "#f7f7f7",
      "#fee090",
      "#fc8d59",
      "#d73027",
    ],
    stops: [0, 0.5, 0.9, 1, 1.1, 1.5, 2],
    labels: [
      "Much Lower",
      "Lower",
      "Slightly Lower",
      "Near Match",
      "Slightly Higher",
      "Higher",
      "Much Higher",
    ],
  },
  relative_maximum: {
    colors: [
      "#4575b4",
      "#91bfdb",
      "#e0f3f8",
      "#f7f7f7",
      "#fee090",
      "#fc8d59",
      "#d73027",
    ],
    stops: [0, 0.5, 0.9, 1, 1.1, 1.5, 2],
    labels: [
      "Much Lower",
      "Lower",
      "Slightly Lower",
      "Near Match",
      "Slightly Higher",
      "Higher",
      "Much Higher",
    ],
  },
  relative_standard_deviation: {
    colors: [
      "#4575b4",
      "#91bfdb",
      "#e0f3f8",
      "#f7f7f7",
      "#fee090",
      "#fc8d59",
      "#d73027",
    ],
    stops: [0, 0.5, 0.9, 1, 1.1, 1.5, 2],
    labels: [
      "Much Less Variable",
      "Less Variable",
      "Slightly Less Variable",
      "Similar Variability",
      "Slightly More Variable",
      "More Variable",
      "Much More Variable",
    ],
  },
  pearson_correlation: {
    colors: ["#2166ac", "#92c5de", "#f7f7f7", "#f4a582", "#b2182b"],
    stops: [-1, -0.5, 0, 0.5, 1],
    labels: [
      "Strong Negative",
      "Moderate Negative",
      "No Linear Correlation",
      "Moderate Positive",
      "Strong Positive",
    ],
  },
  nash_sutcliffe_efficiency: {
    colors: ["#d73027", "#fc8d59", "#91bfdb", "#2166ac"],
    stops: [-1, 0.3, 0.7, 1],
    labels: ["Poor", "Fair", "Good", "Excellent"],
  },
  kling_gupta_efficiency: {
    colors: ["#d73027", "#fc8d59", "#91bfdb", "#2166ac"],
    stops: [-1, 0.3, 0.7, 1],
    labels: ["Poor", "Fair", "Good", "Excellent"],
  },
  count: {
    colors: ["#ffffcc", "#a1dab4", "#41b6c4", "#225ea8"],
    stops: [0, 100, 500, 1000],
    labels: ["Low", "Medium", "High", "Very High"],
  },
  average: {
    colors: ["#ffffcc", "#c2e699", "#78c679", "#238443"],
    stops: [0, 1, 5, 20],
    labels: ["Low", "Medium", "High", "Very High"],
  },
};
