import asyncio
from httpx import HTTPStatusError
from prefect import get_client
from prefect.client.schemas.actions import GlobalConcurrencyLimitCreate
from prefect.exceptions import ObjectAlreadyExists
from prefect.server.schemas.actions import WorkPoolUpdate


async def update_kubernetes_pool():
    async with get_client() as client:
        base_job_template = {
            "variables": {
                "type": "object",
                "properties": {
                    "env": {
                        "type": "object",
                        "title": "Environment Variables",
                        "description": "Environment variables to set when starting a flow run.",
                        "additionalProperties": {
                            "type": "string"
                        }
                    },
                    "name": {
                        "type": "string",
                        "title": "Name",
                        "description": "Name given to infrastructure created by a worker."
                    },
                    "image": {
                        "type": "string",
                        "title": "Image",
                        "example": "docker.io/prefecthq/prefect:2-latest",
                        "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
                    },
                    "labels": {
                        "type": "object",
                        "title": "Labels",
                        "description": "Labels applied to infrastructure created by a worker.",
                        "additionalProperties": {
                            "type": "string"
                        }
                    },
                    "command": {
                        "type": "string",
                        "title": "Command",
                        "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
                    },
                    "namespace": {
                        "type": "string",
                        "title": "Namespace",
                        "default": "default",
                        "description": "The Kubernetes namespace to create jobs within."
                    },
                    "stream_output": {
                        "type": "boolean",
                        "title": "Stream Output",
                        "default": True,
                        "description": "If set, output will be streamed from the job to local standard output."
                    },
                    "cluster_config": {
                        "allOf": [
                            {
                                "$ref": "#/definitions/KubernetesClusterConfig"
                            }
                        ],
                        "title": "Cluster Config",
                        "description": "The Kubernetes cluster config to use for job creation."
                    },
                    "finished_job_ttl": {
                        "type": "integer",
                        "title": "Finished Job TTL",
                        "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
                    },
                    "image_pull_policy": {
                        "enum": [
                            "IfNotPresent",
                            "Always",
                            "Never"
                        ],
                        "type": "string",
                        "title": "Image Pull Policy",
                        "default": "IfNotPresent",
                        "description": "The Kubernetes image pull policy to use for job containers."
                    },
                    "service_account_name": {
                        "type": "string",
                        "title": "Service Account Name",
                        "description": "The Kubernetes service account to use for job creation."
                    },
                    "job_watch_timeout_seconds": {
                        "type": "integer",
                        "title": "Job Watch Timeout Seconds",
                        "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
                    },
                    "pod_watch_timeout_seconds": {
                        "type": "integer",
                        "title": "Pod Watch Timeout Seconds",
                        "default": 60,
                        "description": "Number of seconds to watch for pod creation before timing out."
                    },
                    "cpu_request": {
                        "type": "string",
                        "title": "cpu_request",
                        "description": "cpu_request."
                    },
                    "cpu_limits": {
                        "type": "string",
                        "title": "cpu_limits",
                        "description": "cpu_limits."
                    },
                    "memory_request": {
                        "type": "string",
                        "title": "memory_request",
                        "description": "memory_request."
                    },
                    "memory_limits": {
                        "type": "string",
                        "title": "memory_limits",
                    },
                    "node_selector": {
                        "type": "object",
                        "title": "Node Selector",
                        "description": "Node selector for scheduling pods.",
                        "additionalProperties": {
                            "type": "string"
                        }
                    },
                    "tolerations": {
                        "type": "array",
                        "title": "Tolerations",
                        "description": "Tolerations for scheduling pods.",
                        "items": {
                            "type": "object"
                        }
                    },
                    "image_pull_secrets": {
                        "type": "array",
                        "title": "Image Pull Secrets",
                        "description": "Image pull secrets for pulling images.",
                        "items": {
                            "type": "object"
                        }
                    },
                },
                "definitions": {
                    "KubernetesClusterConfig": {
                        "type": "object",
                        "title": "KubernetesClusterConfig",
                        "required": [
                            "config",
                            "context_name"
                        ],
                        "properties": {
                            "config": {
                                "type": "object",
                                "title": "Config",
                                "description": "The entire contents of a kubectl config file."
                            },
                            "context_name": {
                                "type": "string",
                                "title": "Context Name",
                                "description": "The name of the kubectl context to use."
                            }
                        },
                        "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
                        "secret_fields": [],
                        "block_type_slug": "kubernetes-cluster-config",
                        "block_schema_references": {}
                    }
                },
                "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
            },
            "job_configuration": {
                "env": "{{ env }}",
                "name": "{{ name }}",
                "labels": "{{ labels }}",
                "command": "{{ command }}",
                "namespace": "{{ namespace }}",
                "job_manifest": {
                    "kind": "Job",
                    "spec": {
                        "template": {
                            "spec": {
                                "securityContext": {
                                    "runAsUser": 1000,
                                    "runAsGroup": 1000,
                                    "fsGroup": 1000
                                },
                                "containers": [
                                    {
                                        "env": "{{ env }}",
                                        "args": "{{ command }}",
                                        "name": "prefect-job",
                                        "image": "{{ image }}",
                                        "imagePullPolicy": "{{ image_pull_policy }}",
                                        "resources": {
                                            "limits": {
                                                "cpu": "{{ cpu_limits }}",
                                                "memory": "{{ memory_limits }}"
                                            },
                                            "requests": {
                                                "cpu": "{{ cpu_request }}",
                                                "memory": "{{ memory_request }}"
                                            }
                                        },
                                        "volumeMounts": [
                                            {
                                                "name": "teehr-hub-data-nfs",
                                                "mountPath": "/data"
                                            }
                                        ]
                                    }
                                ],
                                "completions": 1,
                                "parallelism": 1,
                                "restartPolicy": "Never",
                                "serviceAccountName": "{{ service_account_name }}",
                                "nodeSelector": "{{ node_selector }}",
                                "tolerations": "{{ tolerations }}",
                                "imagePullSecrets": "{{ image_pull_secrets }}",
                                "volumes": [
                                    {
                                        "name": "teehr-hub-data-nfs",
                                        "persistentVolumeClaim": {
                                        "claimName": "data-nfs"
                                        }
                                    }
                                ]
                            }
                        },
                        "backoffLimit": 0,
                        "activeDeadlineSeconds": 7200,
                        "ttlSecondsAfterFinished": "{{ finished_job_ttl }}"
                    },
                    "metadata": {
                        "labels": "{{ labels }}",
                        "namespace": "{{ namespace }}",
                        "generateName": "{{ name }}-"
                    },
                    "apiVersion": "batch/v1"
                },
                "stream_output": "{{ stream_output }}",
                "cluster_config": "{{ cluster_config }}",
                "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
                "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}"
            }
        }

        # ToDo we should be able to read the pool and update vs set all now.
        # work_pool = client.read_work_pool(work_pool_name="kubernetes-pool")

        work_pool_update = WorkPoolUpdate(
            base_job_template=base_job_template
        )

        await client.update_work_pool(
            work_pool_name="kubernetes-pool",
            work_pool=work_pool_update
        )


GLOBAL_CONCURRENCY_LIMITS = [
    {"name": "nwps-rfc-fetch", "limit": 8},
]


def _get_limit_id(limit_obj):
    if isinstance(limit_obj, dict):
        return limit_obj.get("id")
    return getattr(limit_obj, "id", None)


def _get_limit_value(limit_obj):
    if isinstance(limit_obj, dict):
        # API payloads can surface either key depending on client/model shape.
        return limit_obj.get("limit", limit_obj.get("concurrency_limit"))

    if hasattr(limit_obj, "limit"):
        return getattr(limit_obj, "limit")
    if hasattr(limit_obj, "concurrency_limit"):
        return getattr(limit_obj, "concurrency_limit")
    return None


async def _find_global_concurrency_limit(client, name: str):
    by_name_candidates = [
        "read_global_concurrency_limit_by_name",
        "get_global_concurrency_limit_by_name",
    ]
    for method_name in by_name_candidates:
        method = getattr(client, method_name, None)
        if method is None:
            continue
        return await method(name=name)

    list_candidates = [
        "read_global_concurrency_limits",
        "read_concurrency_limits",
    ]
    for method_name in list_candidates:
        method = getattr(client, method_name, None)
        if method is None:
            continue

        params = inspect.signature(method).parameters
        kwargs = {}
        if "limit" in params:
            kwargs["limit"] = 500

        limits = await method(**kwargs)
        for limit_obj in limits:
            limit_name = (
                limit_obj.get("name")
                if isinstance(limit_obj, dict)
                else getattr(limit_obj, "name", None)
            )
            if limit_name == name:
                return limit_obj

    return None


async def _delete_global_concurrency_limit(client, name: str) -> None:
    limit_id = None
    existing = await _find_global_concurrency_limit(client, name)
    if existing is not None:
        limit_id = _get_limit_id(existing)

    if limit_id is not None:
        await client.delete_global_concurrency_limit_by_id(id=limit_id)
    else:
        # Fallback: try delete-by-name if available
        method = getattr(client, "delete_global_concurrency_limit", None)
        if method is not None:
            await method(name=name)


async def upsert_global_concurrency_limits():
    async with get_client() as client:
        for gcl in GLOBAL_CONCURRENCY_LIMITS:
            try:
                await client.create_global_concurrency_limit(
                    concurrency_limit=GlobalConcurrencyLimitCreate(
                        name=gcl["name"],
                        limit=gcl["limit"],
                    )
                )
                print(f"Created GCL '{gcl['name']}' with limit={gcl['limit']}")
            except (HTTPStatusError, ObjectAlreadyExists) as e:
                is_conflict = isinstance(e, ObjectAlreadyExists) or (
                    isinstance(e, HTTPStatusError) and e.response.status_code == 409
                )
                if is_conflict:
                    existing = await _find_global_concurrency_limit(client, gcl["name"])
                    existing_limit = _get_limit_value(existing) if existing is not None else None
                    if existing_limit == gcl["limit"]:
                        print(
                            f"GCL '{gcl['name']}' already exists with limit={existing_limit}, no change needed"
                        )
                        continue

                    await _delete_global_concurrency_limit(client, gcl["name"])
                    await client.create_global_concurrency_limit(
                        concurrency_limit=GlobalConcurrencyLimitCreate(
                            name=gcl["name"],
                            limit=gcl["limit"],
                        )
                    )
                    print(
                        f"Recreated GCL '{gcl['name']}' with limit={gcl['limit']} (was {existing_limit})"
                    )
                else:
                    raise


if __name__ == "__main__":
    asyncio.run(update_kubernetes_pool())
    asyncio.run(upsert_global_concurrency_limits())
