#!/usr/bin/env bash
set -euo pipefail

# Verifies cluster-level platform prerequisites expected by app ingress deploys.
# Intended for local use and CI before running Garden deploy for remote clusters.

NAMESPACE="${NAMESPACE:-teehr-hub}"
ISSUER_NAME="${ISSUER_NAME:-letsencrypt-prod}"

check_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: Required command not found: $cmd"
    exit 1
  fi
}

check_cmd kubectl

failures=0

pass() {
  echo "PASS: $1"
}

fail() {
  echo "FAIL: $1"
  failures=$((failures + 1))
}

check_resource() {
  local desc="$1"
  shift
  if "$@" >/dev/null 2>&1; then
    pass "$desc"
  else
    fail "$desc"
  fi
}

echo "Checking platform prerequisites for namespace '$NAMESPACE'..."

check_resource "Kubernetes API reachable" kubectl version --request-timeout=10s
check_resource "Contour HTTPProxy CRD installed" kubectl get crd httpproxies.projectcontour.io
check_resource "cert-manager Certificate CRD installed" kubectl get crd certificates.cert-manager.io
check_resource "cert-manager ClusterIssuer CRD installed" kubectl get crd clusterissuers.cert-manager.io
check_resource "ClusterIssuer '$ISSUER_NAME' exists" kubectl get clusterissuer "$ISSUER_NAME"

# App ingresses reference host-specific TLS secrets generated by cert-manager cert resources.
# This check verifies that at least one expected TLS secret exists in the target namespace.
if kubectl -n "$NAMESPACE" get secret -o name 2>/dev/null | grep -E -- '-tls$' >/dev/null; then
  pass "At least one TLS secret exists in namespace '$NAMESPACE'"
else
  fail "No TLS secrets found in namespace '$NAMESPACE' (expected secrets ending in '-tls')"
fi

if [[ "$failures" -gt 0 ]]; then
  echo ""
  echo "Platform prerequisite check failed with $failures issue(s)."
  exit 1
fi

echo ""
echo "All platform prerequisites look good."
