apiVersion: batch/v1
kind: Job
metadata:
  name: load-secrets
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: load-secrets
        image: prefecthq/prefect:3.2.0-python3.10
        command:
        - python
        - -c
        - |
          # Note, this script needs to be manually copied from
          # load_secrets.py to load-secrets.yaml
          from prefect.blocks.system import Secret
          import os
          print("Running load secrets...")
          api_usgs_pat = os.getenv("API_USGS_PAT")
          Secret(value=api_usgs_pat).save(name="api-usgs-pat", overwrite=True)
          print(f"✅ Successfully loaded api-usgs-pat into Prefect Secret block.")
        env:
        - name: PREFECT_API_URL
          value: http://prefect-server:4200/api
        - name: API_USGS_PAT
          valueFrom:
            secretKeyRef:
              name: prefect-workflow-secrets
              key: api-usgs-pat
      restartPolicy: Never