apiVersion: batch/v1
kind: Job
metadata:
  name: update-job-template
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: update-job-template
        image: prefecthq/prefect:3.2.0-python3.10
        command:
        - python
        - -c
        - |
          # Note, this script needs to be manually copied from
          # load_secrets.py to load-secrets.yaml
          import asyncio
          from prefect import get_client
          from prefect.server.schemas.actions import WorkPoolUpdate


          async def update_kubernetes_pool():
              async with get_client() as client:
                  base_job_template = {
                      "variables": {
                          "type": "object",
                          "properties": {
                              "env": {
                                  "type": "object",
                                  "title": "Environment Variables",
                                  "description": "Environment variables to set when starting a flow run.",
                                  "additionalProperties": {
                                      "type": "string"
                                  }
                              },
                              "name": {
                                  "type": "string",
                                  "title": "Name",
                                  "description": "Name given to infrastructure created by a worker."
                              },
                              "image": {
                                  "type": "string",
                                  "title": "Image",
                                  "example": "docker.io/prefecthq/prefect:2-latest",
                                  "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
                              },
                              "labels": {
                                  "type": "object",
                                  "title": "Labels",
                                  "description": "Labels applied to infrastructure created by a worker.",
                                  "additionalProperties": {
                                      "type": "string"
                                  }
                              },
                              "command": {
                                  "type": "string",
                                  "title": "Command",
                                  "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
                              },
                              "namespace": {
                                  "type": "string",
                                  "title": "Namespace",
                                  "default": "default",
                                  "description": "The Kubernetes namespace to create jobs within."
                              },
                              "stream_output": {
                                  "type": "boolean",
                                  "title": "Stream Output",
                                  "default": True,
                                  "description": "If set, output will be streamed from the job to local standard output."
                              },
                              "cluster_config": {
                                  "allOf": [
                                      {
                                          "$ref": "#/definitions/KubernetesClusterConfig"
                                      }
                                  ],
                                  "title": "Cluster Config",
                                  "description": "The Kubernetes cluster config to use for job creation."
                              },
                              "finished_job_ttl": {
                                  "type": "integer",
                                  "title": "Finished Job TTL",
                                  "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
                              },
                              "image_pull_policy": {
                                  "enum": [
                                      "IfNotPresent",
                                      "Always",
                                      "Never"
                                  ],
                                  "type": "string",
                                  "title": "Image Pull Policy",
                                  "default": "IfNotPresent",
                                  "description": "The Kubernetes image pull policy to use for job containers."
                              },
                              "service_account_name": {
                                  "type": "string",
                                  "title": "Service Account Name",
                                  "description": "The Kubernetes service account to use for job creation."
                              },
                              "job_watch_timeout_seconds": {
                                  "type": "integer",
                                  "title": "Job Watch Timeout Seconds",
                                  "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
                              },
                              "pod_watch_timeout_seconds": {
                                  "type": "integer",
                                  "title": "Pod Watch Timeout Seconds",
                                  "default": 60,
                                  "description": "Number of seconds to watch for pod creation before timing out."
                              },
                              "node_selector": {
                                  "type": "object",
                                  "title": "Node selector string",
                                  "description": "Rules for node selection."
                              },
                              "tolerations": {
                                  "type": "array",
                                  "title": "Tolerations",
                                  "description": "Tolerations."
                              },
                              "image_pull_secrets": {
                                  "type": "array",
                                  "title": "Image pull secrets",
                                  "description": "Image pull secrets."
                              },
                              "cpu_request": {
                                    "type": "string",
                                    "title": "cpu_request",
                                    "description": "cpu_request."
                                },
                                "cpu_limits": {
                                    "type": "string",
                                    "title": "cpu_limits",
                                    "description": "cpu_limits."
                                },
                                "memory_request": {
                                    "type": "string",
                                    "title": "memory_request",
                                    "description": "memory_request."
                                },
                                "memory_limits": {
                                    "type": "string",
                                    "title": "memory_limits",
                                    "description": "memory_request."
                                }
                          },
                          "definitions": {
                              "KubernetesClusterConfig": {
                                  "type": "object",
                                  "title": "KubernetesClusterConfig",
                                  "required": [
                                      "config",
                                      "context_name"
                                  ],
                                  "properties": {
                                      "config": {
                                          "type": "object",
                                          "title": "Config",
                                          "description": "The entire contents of a kubectl config file."
                                      },
                                      "context_name": {
                                          "type": "string",
                                          "title": "Context Name",
                                          "description": "The name of the kubectl context to use."
                                      }
                                  },
                                  "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
                                  "secret_fields": [],
                                  "block_type_slug": "kubernetes-cluster-config",
                                  "block_schema_references": {}
                              }
                          },
                          "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
                      },
                      "job_configuration": {
                          "env": "{{ env }}",
                          "name": "{{ name }}",
                          "labels": "{{ labels }}",
                          "command": "{{ command }}",
                          "namespace": "{{ namespace }}",
                          "job_manifest": {
                              "kind": "Job",
                              "spec": {
                                  "template": {
                                      "spec": {
                                          "containers": [
                                              {
                                                  "env": "{{ env }}",
                                                  "args": "{{ command }}",
                                                  "name": "prefect-job",
                                                  "image": "{{ image }}",
                                                  "imagePullPolicy": "{{ image_pull_policy }}",
                                                  "resources": {
                                                        "limits": {
                                                            "cpu": "{{ cpu_limits }}",
                                                            "memory": "{{ memory_limits }}"
                                                        },
                                                        "requests": {
                                                            "cpu": "{{ cpu_request }}",
                                                            "memory": "{{ memory_request }}"
                                                        }
                                                    }
                                              }
                                          ],
                                          "completions": 1,
                                          "parallelism": 1,
                                          "restartPolicy": "Never",
                                          "serviceAccountName": "{{ service_account_name }}",
                                          "nodeSelector": "{{ node_selector }}",
                                          "tolerations": "{{ tolerations }}",
                                          "imagePullSecrets": "{{ image_pull_secrets }}"
                                        }
                                  },
                                  "backoffLimit": 0,
                                  "activeDeadlineSeconds": 7200,
                                  "ttlSecondsAfterFinished": "{{ finished_job_ttl }}"
                              },
                              "metadata": {
                                  "labels": "{{ labels }}",
                                  "namespace": "{{ namespace }}",
                                  "generateName": "{{ name }}-"
                              },
                              "apiVersion": "batch/v1"
                          },
                          "stream_output": "{{ stream_output }}",
                          "cluster_config": "{{ cluster_config }}",
                          "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
                          "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}"
                      }
                  }

                  # ToDo we should be able to read the pool and update vs set all now.
                  # work_pool = client.read_work_pool(work_pool_name="kubernetes-pool")

                  work_pool_update = WorkPoolUpdate(
                      base_job_template=base_job_template
                  )

                  await client.update_work_pool(
                      work_pool_name="kubernetes-pool",
                      work_pool=work_pool_update
                  )

          asyncio.run(update_kubernetes_pool())

        env:
        - name: PREFECT_API_URL
          value: http://prefect-server:4200/api
      restartPolicy: Never